import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ShieldCheck, Mail, ArrowLeft } from "lucide-react";
import Link from "next/link";
export default function ForgotPasswordPage() {
    return (_jsx("div", { className: "min-h-screen bg-slate-900 flex items-center justify-center p-4", children: _jsxs("div", { className: "w-full max-w-md", children: [_jsx("div", { className: "mb-6", children: _jsxs(Link, { href: "/login", className: "inline-flex items-center text-sm text-slate-400 hover:text-white transition-colors", children: [_jsx(ArrowLeft, { className: "w-4 h-4 mr-2" }), "Back to Sign In"] }) }), _jsxs(Card, { className: "shadow-lg border-slate-700 bg-slate-800/90 backdrop-blur-sm", children: [_jsxs(CardHeader, { className: "text-center pb-6", children: [_jsx("div", { className: "flex items-center justify-center mb-4", children: _jsx("div", { className: "flex items-center justify-center w-12 h-12 bg-amber-400 rounded-xl", children: _jsx(ShieldCheck, { className: "w-7 h-7 text-slate-800" }) }) }), _jsx(CardTitle, { className: "text-2xl font-bold text-white", children: "Reset Password" }), _jsx(CardDescription, { className: "text-slate-300", children: "Enter your email address and we'll send you a link to reset your password." })] }), _jsxs(CardContent, { className: "space-y-6", children: [_jsxs("form", { className: "space-y-4", children: [_jsxs("div", { className: "space-y-2", children: [_jsx(Label, { htmlFor: "email", className: "text-sm font-medium text-white", children: "Email Address" }), _jsx(Input, { id: "email", type: "email", placeholder: "Enter your email address", className: "h-11 bg-slate-700 border-slate-600 text-white placeholder:text-slate-400 focus:border-amber-400 focus:ring-amber-400/20", required: true })] }), _jsxs(Button, { type: "submit", className: "w-full h-11 text-base font-medium bg-amber-400 text-slate-800 hover:bg-amber-500", children: [_jsx(Mail, { className: "w-4 h-4 mr-2" }), "Send Reset Link"] })] }), _jsxs("div", { className: "text-center text-sm text-slate-400", children: ["Remember your password?", " ", _jsx(Link, { href: "/login", className: "text-amber-400 hover:text-amber-300 font-medium transition-colors", children: "Sign in here" })] })] })] }), _jsxs("div", { className: "mt-6 text-center text-xs text-slate-400", children: ["If you don't receive an email within a few minutes, please check your spam folder or", " ", _jsx(Link, { href: "/contact", className: "text-amber-400 hover:text-amber-300 transition-colors", children: "contact support" })] })] }) }));
}
